output-format: grouped

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

uses:
  - django

#mypy:
#  run: true
#  options:
#    ignore-missing-imports: true
#    follow-imports: skip
#    allow:
#      - untyped-globals
#    disallow:
#      - any-expr

pep8:
  full: true
  disable:
    - D100
    - D101
    - D102
    - D103
    - D105
    - D205
    - D400
    - N802  # function name should be lowercase, breaks on tests
  options:
    max-line-length: 120

pyflakes:
  disable:
    - F999
    - F401

pylint:
  disable:
    - broad-except
    - too-few-public-methods
    - invalid-name
    - no-self-use
    - no-member
  options:
    max-line-length: 120

dodgy:
  run: true

ignore-paths:
  - venv
  - env
  - .env
  - .venv

ignore-patterns:
  - .+/migrations/.+
  - .+/settings/.+
  - .+manage.+
